package postgres

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/abibby/salusa/database/dialects"
	"github.com/abibby/salusa/database/dialects/generic"
)

type PosgtgresCore struct {
	bindingNumber int
}

func (*PosgtgresCore) Identifier(s string) string {
	if s == "*" {
		return s
	}
	parts := strings.Split(s, ".")
	for i, p := range parts {
		if p == "*" {
			continue
		}
		parts[i] = "\"" + p + "\""
	}
	return strings.Join(parts, ".")
}

func (*PosgtgresCore) DataType(t dialects.DataType) string {
	switch t.Name {
	case dialects.DataTypeBlob.Name:
		return "BYTEA"
	case dialects.DataTypeString.Name:
		s := t.Size
		if s == 0 {
			s = 255
		}
		return fmt.Sprintf("VARCHAR(%d)", s)
	case dialects.DataTypeEnum.Name:
		panic("not implemented")

	case dialects.DataTypeBoolean.Name:
		return "BOOLEAN"

	case dialects.DataTypeDate.Name, dialects.DataTypeDateTime.Name:
		return "TIMESTAMP"

	case dialects.DataTypeFloat32.Name:
		return "REAL"
	case dialects.DataTypeFloat64.Name:
		return "DOUBLE PRECISION"

	case dialects.DataTypeInt8.Name, dialects.DataTypeInt16.Name, dialects.DataTypeUInt8.Name, dialects.DataTypeUInt16.Name:
		return "SMALLINT"
	case dialects.DataTypeInt32.Name, dialects.DataTypeUInt32.Name:
		return "INTEGER"
	case dialects.DataTypeInt64.Name, dialects.DataTypeUInt64.Name:
		return "BIGINT"

	case dialects.DataTypeJSON.Name:
		return "JSON"
	}
	return string(t.Name)
}

func (*PosgtgresCore) CurrentTime() string {
	return "CURRENT_TIMESTAMP()"
}

func (*PosgtgresCore) AutoIncrement() string {
	return "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
}

func (s *PosgtgresCore) Escape(v any) string {
	switch v := v.(type) {
	case string:
		return "'" + strings.ReplaceAll(v, "'", "''") + "'"
	case int, int8, int16, int32, int64,
		uint, uint8, uint16, uint32, uint64,
		float32, float64:
		return fmt.Sprint(v)
	case bool:
		if v {
			return "TRUE"
		} else {
			return "FALSE"
		}
	default:
		b, err := json.Marshal(v)
		if err != nil {
			panic(fmt.Errorf("failed to escape value: %w", err))
		}
		return s.Escape(string(b))
	}
}

func (p *PosgtgresCore) Binding() string {
	p.bindingNumber++
	return fmt.Sprintf("$%d", p.bindingNumber)
}

func (s *PosgtgresCore) Features() dialects.Features {
	return dialects.Features{
		Returning: true,
	}
}

func New() dialects.Dialect {
	return generic.New(&PosgtgresCore{})
}

func UsePostgres() {
	dialects.Register("postgres", New)
}
func init() {
	UsePostgres()
}
