version: "2"
linters:
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - staticcheck
        text: "SA1029: should not use built-in type string as key for value; define your own type to avoid collisions"

      - linters:
          - errcheck
        text: "Error return value of `fmt.Fprintf` is not checked"

      - linters:
          - errcheck
        text: "Error return value of `[^`]+\\.Close` is not checked"
